// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning={true} >
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
  
// }

'use client';
import './globals.css';
import { Poppins } from "next/font/google";
import { BookmarkProvider } from '@/context/BookmarkContext';
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import TokenStorage from '@/components/TokenStorage';


// Load Google Fonts
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});



export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} font-sans`}>
        <SessionProvider>
          <BookmarkProvider>
            <Toaster position="right-bottom" reverseOrder={false} />
            <TokenStorage />
            {children}
          </BookmarkProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
